 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
   workflow_dispatch:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: RICKY_SENSEI/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: RICKY_SENSEI
            # Text on contribution graph 
            text: RICKY SENSEI
       - uses: RICKY_SENSEI/simple-push-action@v1
